version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1602462450
layout:
  header: {  }
  /navigation/: {  }
  /main/:
    -
      - 'onepage-menu-4512 20'
      - 'system-content-4739 80'
  footer: {  }
  offcanvas:
    -
      - 'mobile-menu-8331 50'
      - 'mobile-menu-3877 50'
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    attributes:
      position: g-offcanvas-left
      class: ''
      extra: {  }
      swipe: '1'
      css3animation: '1'
content:
  onepage-menu-4512:
    title: 'OnePage Menu'
    attributes:
      stickyoffset: '130'
      smoothscrolloffset: '120'
      boundary: '#g-footer'
      items:
        -
          title: Happenings
          icon: ''
          link: 'http://lapct2.local/happenings/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          name: Happenings
        -
          title: Calendar
          icon: ''
          link: 'http://lapct2.local/events/month/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          extra: {  }
          name: Calendar
        -
          title: 'Exposure Weekend (Portfolio Reviews)'
          icon: ''
          link: 'http://lapct2.local/happenings/exposure-weekendportfolio-reviews/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          extra: {  }
          name: 'Exposure Weekend (Portfolio Reviews)'
        -
          title: 'STREET WEEK in LA'
          icon: ''
          link: 'http://lapct2.local/programs-services/street-shooting-program/street-week-in-la/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          extra: {  }
          name: 'STREET WEEK in LA'
        -
          title: 'Holiday Party'
          icon: ''
          link: 'http://lapct2.local/happenings/holiday-party/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          extra: {  }
          name: 'Holiday Party'
  mobile-menu-8331:
    title: 'Mobile Menu'
