name: about_us
timestamp: 1606099734
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1602462450
positions: {  }
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  onepage-menu:
    onepage-menu-4512: 'OnePage Menu'
  content:
    system-content-4739: 'Page Content'
  mobile-menu:
    mobile-menu-8331: 'Mobile Menu'
    mobile-menu-3877: Mobile-menu
  spacer:
    spacer-4857: Spacer
    spacer-5367: Spacer
  menu:
    menu-7374: Menu
    menu-6186: Menu
  logo:
    logo-1195: 'Logo / Image'
    logo-7232: 'Logo / Image'
  custom:
    custom-8419: 'Custom HTML'
    custom-8229: 'Custom HTML'
    custom-2397: 'Custom HTML'
    custom-7889: 'Custom HTML'
    custom-3964: 'Custom HTML'
  copyright:
    copyright-7725: Copyright
  totop:
    totop-1984: 'To Top'
inherit:
  default:
    header: header
    footer: footer
    spacer-4857: spacer-8928
    menu-7374: menu-9715
    logo-1195: logo-5008
    menu-6186: menu-1653
    logo-7232: logo-8019
    custom-8419: custom-7037
    custom-8229: custom-7583
    custom-2397: custom-8770
    custom-7889: custom-9923
    custom-3964: custom-2633
    copyright-7725: copyright-2500
    spacer-5367: spacer-4014
    totop-1984: totop-9413
