version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1602462450
layout:
  header: {  }
  /navigation/: {  }
  /main/:
    -
      - 'onepage-menu-4512 20'
      - 'system-content-4739 80'
  footer: {  }
  offcanvas:
    -
      - 'mobile-menu-8331 50'
      - 'mobile-menu-3877 50'
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    attributes:
      position: g-offcanvas-left
      class: ''
      extra: {  }
      swipe: '1'
      css3animation: '1'
content:
  onepage-menu-4512:
    title: 'OnePage Menu'
    attributes:
      stickyoffset: '130'
      smoothscrolloffset: '120'
      boundary: '#g-footer'
      items:
        -
          title: 'About Us'
          icon: ''
          link: 'http://lapct2.local/about-us/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          extra: {  }
          name: 'About Us'
        -
          title: 'History & Mission Statement'
          icon: ''
          link: 'http://lapct2.local/about-us/history-mission-statement/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          name: 'History & Mission Statement'
        -
          title: 'Julia Dean, Executive Director'
          icon: ''
          link: 'http://lapct2.local/about-us/julia-dean-executive-director/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          name: 'Julia Dean, Executive Director'
        -
          title: Staff
          icon: ''
          link: 'http://lapct2.local/about-us/staff/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          name: Staff
        -
          title: 'Board of Directors'
          icon: ''
          link: 'http://lapct2.local/about-us/board-of-directors/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          name: 'Board of Directors'
        -
          title: 'Officers & Advisors'
          icon: ''
          link: 'http://lapct2.local/about-us/officer-advisors/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          name: 'Officers & Advisors'
        -
          title: Testimonials
          icon: ''
          link: 'http://lapct2.local/about-us/testimonials/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          name: Testimonials
        -
          title: Press
          icon: ''
          link: 'http://lapct2.local/about-us/press/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          name: Press
        -
          title: 'Community Outreach'
          icon: ''
          link: 'http://lapct2.local/about-us/community-outreach/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          name: 'Community Outreach'
        -
          title: 'Sponsors & Partners'
          icon: ''
          link: 'http://lapct2.local/about-us/sponsors-partners/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          name: 'Sponsors & Partners'
        -
          title: 'Contact Us'
          icon: ''
          link: 'http://lapct2.local/about-us/contact-us/'
          subtitle1: ''
          subicon1: ''
          sublink1: ''
          subtitle2: ''
          subicon2: ''
          sublink2: ''
          subtitle3: ''
          subicon3: ''
          sublink3: ''
          subtitle4: ''
          subicon4: ''
          sublink4: ''
          subtitle5: ''
          subicon5: ''
          sublink5: ''
          class: ''
          name: 'Contact Us'
  mobile-menu-8331:
    title: 'Mobile Menu'
