version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1599577368
layout:
  navigation: {  }
  /header/:
    -
      - owlcarousel-2455
  /intro/: {  }
  /features/:
    -
      - system-content-5664
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'mainbar 75': {  }
      -
        'sidebar 25': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: '2'
      class: g-flushed
      variations: ''
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  owlcarousel-2455:
    title: 'Owl Carousel'
    attributes:
      nav: enable
      dots: enable
      autoplay: disable
      autoplaySpeed: ''
      imageOverlay: enable
      items:
        -
          class: ''
          image: 'gantry-media://owlcarousel/Julia-Dean-53.jpg'
          title: 'INSIDE PHOTOGRAPHY'
          desc: 'Guest Julia Dean - November 12 , 5 pm PST'
          link: 'https://lacphoto.org/events/inside-photography-conversations-with-contemporary-photographers-2020/'
          linktext: 'CLICK FOR DETAILS'
          buttonclass: button-outline
          disable: '0'
          name: 'Item 1'
        -
          class: ''
          image: 'gantry-media://owlcarousel/Cover-Image.jpg'
          title: 'EDUCAIONAL CATALOG'
          desc: 'SUMMER/FALL 2020 SEASON'
          link: 'http://gantry.org/downloads'
          linktext: 'DOWNLOAD/VIEW CATALOG'
          buttonclass: button-outline
          disable: '0'
          name: 'Item 2'
    block:
      variations: 'nomarginall nopaddingall'
