name: programs-services
timestamp: 1612309886
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1602462450
positions: {  }
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  onepage-menu:
    onepage-menu-9812: 'OnePage Menu'
  content:
    system-content-8192: 'Page Content'
  spacer:
    spacer-2004: Spacer
    spacer-3844: Spacer
  menu:
    menu-5590: Menu
    menu-3835: Menu
  logo:
    logo-7029: 'Logo / Image'
    logo-1457: 'Logo / Image'
  custom:
    custom-5321: 'Custom HTML'
    custom-8380: 'Custom HTML'
    custom-2219: 'Custom HTML'
    custom-3737: 'Custom HTML'
    custom-9126: 'Custom HTML'
  copyright:
    copyright-8411: Copyright
  totop:
    totop-2859: 'To Top'
  mobile-menu:
    mobile-menu-2034: 'Mobile Menu'
    mobile-menu-8465: Mobile-menu
inherit:
  default:
    header: header
    footer: footer
    spacer-2004: spacer-8928
    menu-5590: menu-9715
    logo-7029: logo-5008
    menu-3835: menu-1653
    logo-1457: logo-8019
    custom-5321: custom-7037
    custom-8380: custom-7583
    custom-2219: custom-8770
    custom-3737: custom-9923
    custom-9126: custom-2633
    copyright-8411: copyright-2500
    spacer-3844: spacer-4014
    totop-2859: totop-9413
  membership:
    offcanvas: offcanvas
    mobile-menu-2034: mobile-menu-8331
    mobile-menu-8465: mobile-menu-3877
