name: membership
timestamp: 1612306941
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1602462450
positions: {  }
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  onepage-menu:
    onepage-menu-4512: 'OnePage Menu'
  content:
    system-content-4739: 'Page Content'
  mobile-menu:
    mobile-menu-8331: 'Mobile Menu'
    mobile-menu-3877: Mobile-menu
  spacer:
    spacer-5128: Spacer
    spacer-6737: Spacer
  menu:
    menu-4922: Menu
    menu-8828: Menu
  logo:
    logo-5119: 'Logo / Image'
    logo-2583: 'Logo / Image'
  custom:
    custom-4571: 'Custom HTML'
    custom-8022: 'Custom HTML'
    custom-3874: 'Custom HTML'
    custom-6123: 'Custom HTML'
    custom-7926: 'Custom HTML'
  copyright:
    copyright-9465: Copyright
  totop:
    totop-2121: 'To Top'
inherit:
  default:
    header: header
    footer: footer
    spacer-5128: spacer-8928
    menu-4922: menu-9715
    logo-5119: logo-5008
    menu-8828: menu-1653
    logo-2583: logo-8019
    custom-4571: custom-7037
    custom-8022: custom-7583
    custom-3874: custom-8770
    custom-6123: custom-9923
    custom-7926: custom-2633
    copyright-9465: copyright-2500
    spacer-6737: spacer-4014
    totop-2121: totop-9413
