name: _offline
timestamp: 1612306941
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1602462450
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-2824: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-9851: Menu
  messages:
    system-messages-7331: 'System Messages'
  content:
    system-content-6758: 'Page Content'
  copyright:
    copyright-5707: Copyright
  spacer:
    spacer-6477: Spacer
  branding:
    branding-8631: Branding
  mobile-menu:
    mobile-menu-6581: Mobile-menu
inherit: {  }
