version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1602462450
layout:
  /header/:
    -
      - 'logo-2824 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-9851
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-7331
    -
      - system-content-6758
  /footer/:
    -
      - position-footer
    -
      - 'copyright-5707 40'
      - 'spacer-6477 30'
      - 'branding-8631 30'
  offcanvas:
    -
      - mobile-menu-6581
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
