version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1602462450
layout:
  header: {  }
  /navigation/: {  }
  /showcase/:
    -
      - system-content-1649
  /feature/: {  }
  /main/: {  }
  /subfeature/: {  }
  footer: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: default
      include:
        - children
        - attributes
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  showcase:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  subfeature:
    type: section
    attributes:
      class: flush
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  system-content-1649:
    block:
      variations: 'nomarginall nopaddingall'
