name: _error
timestamp: 1612309886
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1602462450
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-8628: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-9066: Menu
  messages:
    system-messages-1416: 'System Messages'
  content:
    system-content-2653: 'Page Content'
  copyright:
    copyright-9453: Copyright
  spacer:
    spacer-2277: Spacer
  branding:
    branding-9646: Branding
  mobile-menu:
    mobile-menu-5862: Mobile-menu
inherit: {  }
