name: _body_only
timestamp: 1612309886
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1602462450
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-7339: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-2713: Menu
  messages:
    system-messages-8862: 'System Messages'
  content:
    system-content-8851: 'Page Content'
  copyright:
    copyright-3438: Copyright
  spacer:
    spacer-6717: Spacer
  branding:
    branding-9264: Branding
  mobile-menu:
    mobile-menu-9263: Mobile-menu
inherit: {  }
